name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Some action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions-a
        with:
          MY_NAME: "Mona"
